# Generated by Django 4.1.3 on 2022-11-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
