# Generated by Django 4.1.3 on 2022-11-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0002_rename_series_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
